language: java
sudo: false
notifications:
  hipchat:
    rooms:
      secure: qCsPwS3Zp23mDYDyNcz7YHwH8ACN9afGkKC8piAnGfsZB6V/DgeXMXbuf+gBzJTTmLvwi5Pcd+X26ESsySCog9zpDSHGZLNkdtJvrqFqiHCJWZ6TpuyqxoUZYnrOCWEKfsAOfFLg9SGXJDLdJ7hQF1cWI8d+NQTNIbjusYsv805jVDER2Qt9Ve8NfdH+0J3bYyL++ZJVE6KEZdCDMor9FtnOU07vQSRrmWPivwszoCBMvl3lIYYWeXdEWjewvFix1fzf1JcANKzQMzOekjOxsaJ/pEh0l/t7MxWKFUyrCnUYRfeZBSNPzPOLctIXojqQOEUv9fVPNIRjm+ahlELsJSyoBjHCd1yVVLVPgKlFbgilN6sbS6WneC1En0Z1dzo1JgpM8GRrdRgGHvxrzvG02TUXo403IMjhgsDBn7Ml1rSaFX/9krBSKNzCXLcdzCixCghJ+fGVF7Dyy4Rrw73FK4qhCkQhYwMVeO0N/S/6ZBtge3eOVRwS98QACidt6diOk6+zUr6yyM1uHxOtTPQ8tHlG8zOzr3G4JTQWL4EOnlpCjXFuNnlHkwZ0zwbE6rdzZHvoUX668lSNoDfexIE5wMtXUrcFUIxEM/UdfO6p+ZAVq401G/a4o/G5C6+s3T8iyvNSO074LL66srWDuLI1CRLiHRBy4o/7dHTL2CxVuVg=
deploy:
  provider: releases
  api_key:
    secure: FYEawlA7vg2MPzM/WTIdn3/TG4rDfVfDBMnEaZDIU+YeKip+l9iKF7qTqc9OaEEKkzyGwaVnjK8XLlPURr/niWUowTz6NF6eID/f5T3kPPu+mM1+guPwiFC+w3nYnscvRoit9ESVMW49Gw9foolSS0CHfjBh2MNmJjCAc6xSc1GdxIOi/3w9TfgqdbgoxruBwlD8NTaond2K/Iow4xYy4shsd8bVJQcrFDL59dQ6GlRmHLBMhyjWRSa6iugYqAeHycWryMKGiMEb5/uoUMfw4OyPat0hr07X5bEVMV1mbZUSZPP81BDHtZI98RjI5Q8dS7Owx99oplaU+L9Bkm1vaGZDjVYcWemqjt9my1CLjN6KUvaou6JrXEAGb4U8+M4Z8mhmRwQOgpLl0vhp53xg8KA4XUFrg0da0kREu8VdKU7iv5fdn0Ta7ulBBvQ+YnVxwOYoNl8mIA9QfAQV+EZlQr7GJEGFxu2Vs2+6nyuqmuFHJMC+vKjQiVaQD99UpETgmCEHjnxZKTtzm5fVA22k0QN6X9k3/c5v4wlHDkeV/gObWZYWYZbO3SAZ8z8PDCQmPHjxUca/fXpGOT+L0eoL3cJgcYWumJmpb5HUAitq1mUbPSe8YWLegNdZpoqcxCwy0QaE1WsVimv6zVDdKEEsZaVb/Q9eed4+Qqs6JpSZlN0=
  file: build/distributions/xld-liferay-plugin-1.0.0.RC5.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-liferay-plugin
