language: java
sudo: false
notifications:
  hipchat:
    rooms:
      secure: qCsPwS3Zp23mDYDyNcz7YHwH8ACN9afGkKC8piAnGfsZB6V/DgeXMXbuf+gBzJTTmLvwi5Pcd+X26ESsySCog9zpDSHGZLNkdtJvrqFqiHCJWZ6TpuyqxoUZYnrOCWEKfsAOfFLg9SGXJDLdJ7hQF1cWI8d+NQTNIbjusYsv805jVDER2Qt9Ve8NfdH+0J3bYyL++ZJVE6KEZdCDMor9FtnOU07vQSRrmWPivwszoCBMvl3lIYYWeXdEWjewvFix1fzf1JcANKzQMzOekjOxsaJ/pEh0l/t7MxWKFUyrCnUYRfeZBSNPzPOLctIXojqQOEUv9fVPNIRjm+ahlELsJSyoBjHCd1yVVLVPgKlFbgilN6sbS6WneC1En0Z1dzo1JgpM8GRrdRgGHvxrzvG02TUXo403IMjhgsDBn7Ml1rSaFX/9krBSKNzCXLcdzCixCghJ+fGVF7Dyy4Rrw73FK4qhCkQhYwMVeO0N/S/6ZBtge3eOVRwS98QACidt6diOk6+zUr6yyM1uHxOtTPQ8tHlG8zOzr3G4JTQWL4EOnlpCjXFuNnlHkwZ0zwbE6rdzZHvoUX668lSNoDfexIE5wMtXUrcFUIxEM/UdfO6p+ZAVq401G/a4o/G5C6+s3T8iyvNSO074LL66srWDuLI1CRLiHRBy4o/7dHTL2CxVuVg=
deploy:
  provider: releases
  api_key:
    secure: VCLFgZ77ppDlMEM/Z6KiwG0MsW4SxVBlI3cgTn/L+1F6PWj9J40bT4Gp11ymydiO1P6GdPsBqUcBjo0KbeNmC6DdjEvAoJKrcBEH5w4OB0xk65ckBs4XOh6NLliMHHc9cLgo6nMNaFp04UGfngMxardani/CL4X+Llid04lQJls=
  file: build/distributions/xld-liferay-plugin-1.0.0.RC5.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-liferay-plugin
