language: java
sudo: false
notifications:
  slack:
    secure: EDk7kSxITVaQtRjyRF4o3ayMRlTpbhCROwtyBuKCxNdF5KJbMwbOBCIsBCFt/nobg5LSAdY3z1oQj831N5kMKuNPQgrZ1qEoL5oYE7o1f6LDP6wSCiwEarTZjVN6u0i3NMrVLK7Tp8zH8Np9NzgZ1imGs8s/laQrZb3jp1RmmBqg7hxFsQGLTUVFWbLJs7BEKHGgAFqDQGG7SJdbDf2d/NqU8FNwwrczX6WOdNY3WCULdANmBsSGZZz5tvRGU6sGRI7MLas+RJDC2/jBaYq9QKfXCMw70B/ERCm8gmeYaL6I3l0p+ovCG8fJjbzHyfFvMCjKSfJdcGsSwImXHEs0IhdiDo80iA3z+Q8Rqo7HIdCOGrDIWpO4bqTwu8O8Yf0AErMjyJ8tTVvjoZFfjHaFChlSio1raUa0OQnXZZ7b4Tz1B09chYJxe4zugw155rajNNQLWeuCT0CNW98UdxON9eBRf9G44Wq9ZBlTz9L9vmLv6TY6wBoF5Jafg/iNzaktE2nYV33XUyTQAOKiDdrzRQkgkeKU1eSD4+jmoVCXD+gtTZzSYIaaUtow3Sh0U7QeuR+vfeFCeL28aQYxzVre6X5PsqBzPXIWEB8lwAuaOY/HJkbk427Zs8n1NFUpDWrkdIyemOqIRjjHL8JKCxjNEqo/Hpo6Svr0aUdksCk/7vo=
deploy:
  provider: releases
  api_key:
    secure: QUVFXX915rVNFb+wYuKrMMkqO6QMDqHhJqcJ27G5BQekCqF5ma3yyAm9JDWTavlagCj03FzdISwgybOmhslTMhqe9cmD/PpR8+pCZqO1p1T8quRpR6r2p9oHGgV6iWm+WPKpcqr+4gWW4pa+3Sz7KcRsVHj7hF6/P/b4SFdg+qOD4+rObkXSdUT9eVqAeMkTA9Vess/YIQVWpL9z4E70PEsEGfY+SK4G6M3JR0bmpHlOVDkFhzoCj4VvWpETRYFnZ1GfEavnJ+p8Y+t2E2PSwpeVo7uMJZBxwPexeO3AywAscZGRUbxCp5FnkmgRpgeUbkUByzxeiUW5ampIsV1zrVgT4js2cm6+j0zs+Rk4ywJw8E2SC5ULyKfZ/ekQHKf4oijrZVqMA5ImLsHMDYquIgyXtfW5w/FttU64izCNZ3Yfx3eVXTfokjwCMBWmFaqdlL8acwWeFt6g9ql2O20OwVjbYSjQBT4TyMdqFtzVHevlCEo/edqbSnSjTJo8fERqF6qm8HVpZeeNj873z2AbX+1/u/zTCaTl6UmNFlqwlUT47Qby7R0ju0mZjh7wYMQt/FrQQm270EGvx3PdQE/uQcAuH75tCJZZD8sV3Udfqss3uke540V8W0ky01mpqsjquLFKfujQDJpLrmL8dWqodwcaWPfRu7DpqeW37iJSl1Y=
  file: build/distributions/xld-liferay-plugin-1.0.0.RC5.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-liferay-plugin
